#This is not nice, do not use

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-messaging-topology
spec:
  project: default
  source:
    repoURL: 'https://github.com/rabbitmq/messaging-topology-operator'
    path: config/installation
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'rabbitmq'

