apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
spec:
  destination:
    name: ''
    namespace: 'rabbitmq-system'
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 3.10.5
    chart: rabbitmq-cluster-operator
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
